Update of OWL-Time ontology, extended with rdfs:label, rdfs:comment a…
w3c/sdw pull request #1002
Opened 2018-01-18 20:48 UTC by marianofl1971

…nd skos:definition in Spanish for each definition where they were formerly just in English.

2018-02-04 23:09 UTC, dr-shorthair commented
That’s helpful. 
I found an additional stray assertion:

:intervalEquals owl:propertyDisjointWith :intervalIn . 

This may be correct, but is a semantic modification to what was agreed so can’t be slipped through in this way. 

Also: \n\n linefeeds inside strings are not reliably valid RDF. Turtle supports multi-line text inside triple quotes. 

Finally – the rdfs:Description type assertions are redundant in the .ttl and .nt versions at least. 
I can see how they might have sneaked in because of moving the translations to a separate block, but they can be removed from the .ttl and .nt versions at least.

2018-02-04 23:18 UTC, dr-shorthair requested changes
That’s helpful.
I found an additional stray assertion:

:intervalEquals owl:propertyDisjointWith :intervalIn .

This may be correct, but is a semantic modification to what was agreed so can’t be slipped through in this way.

Also: \n\n linefeeds inside strings are not reliably valid RDF. Turtle supports multi-line text inside triple quotes.

Finally – the rdfs:Description type assertions are redundant in the .ttl and .nt versions at least.
I can see how they might have sneaked in because of moving the translations to a separate block, but they can be removed from the .ttl and .nt versions at least.

2018-02-20 07:22 UTC, dr-shorthair approved these changes
Looks good now. Thanks for the translations.

2018-02-20 07:22 UTC, merged

2018-02-20 07:31 UTC, chris-little reviewed
The Spanish translation is welcome.  The structure looks fine to me.

2018-02-20 10:09 UTC, marianofl1971 commented
Thanks a lot!

Mariano

2018-02-20 8:22 GMT+01:00 Simon Cox <notifications@github.com>:

> Merged #1002 <https://github.com/w3c/sdw/pull/1002>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/sdw/pull/1002#event-1481805973>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AHng2d1_pXo_0SWzgBUv9DxzBWQ_lLonks5tWnK9gaJpZM4Rjir5>
> .
>