Fixed several issues in SSN where decision have been made, but not implemented yet.
w3c/sdw pull request #694
Opened 2017-04-13 07:43 UTC by arminhaller

Please do have a close look at this Pull request!
The Device/SensingDevice has not been implemented yet, waiting for kjano.

2017-04-13 10:56 UTC, maximelefrancois86 requested changes
a lot of comments, 

pull request #697 proposes a resolution to most of these comments.

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                 rdfs:label "has subsystem" .
label should be "has sub system" ?

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                     rdfs:comment "An identifiable characteristic that represents the extent of the Sensor's or Actuator's useful life. Might include, for example, total battery life or number of rec
An identifiable characteristic that represents the extent of the System's useful life. Might be for example BatteryLifetime  or number of recharges, or, for Sensors that are used only a fixed number of times, the number of Observations that can be made before the sensing capability is depleted.

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                        rdfs:comment "Relation from a SurvivalRange of a System to a Property describing the survival qualities of the system." ;
Relation from a SurvivalRange of a System to a SurvivalProperty describing the extent of the System's useful life.

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
>                         rdfs:seeAlso "http://www.w3.org/2005/Incubator/ssn/wiki/SSN_Deploy#Deployment" .
some of the seeAlso are kept, other are deleted. 
Suggest we only keep them in the old SSN, and delete them all here

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                rdfs:comment "Describes the prevailing environmental conditions for MeasurementCapabilites, OperatingConditions and SurvivalRanges. Used, for example, to say that a sensor has a parti
can be split in a rdfs:comment and a skos:example ?

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                 rdfs:comment "Relation between a producer and a produced entity. For example, between a Sensor and the produced Output." ;
isProducedBy should be replaced by isResultOf

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +              skos:example "For example, wind speed of 10-60m/s is expressed as a condition linking a quality, wind speed, a unit of measurement, metres per second, and a set of values, 10-60, and ma
mention of unit of measurement here is confusing. Should be rewritten once ACTION-318 is completed

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                             skos:example "For example, as well as Deployment, installation, maintenance, deployment of further sensors and the like would all be classified under DeploymentRelatedPro
repetition of "Deployment" here

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                        rdfs:comment "Schedule of maintenance for a System, Sensor or Actuator in the specified conditions." ;
Schedule of maintenance for a System in the specified conditions.

(can also apply to Sampler)

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                        rdfs:comment "Power range in which a System, Sensor or Actuator is expected to operate." ;
Power range in which a System is expected to operate.

(can apply to any system)

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                   rdfs:comment "The environmental conditions and characteristics of a System's, Sensor's or Actuator's normal operating environment.  Can be used to specify for example the standard
System's, Sensor's or Actuator's --> System's

(sensors and actuators are systems)

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                     rdfs:comment "The set of values that the sensor can return as the Result of an Observation under the defined conditions with the defined MeasurementProperties. If no Conditions a
observed ObservableProperty ?

try to avoid the use of "quality", which was strongly related to the DUL class

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +sosa:Sensing rdf:type owl:Class ;
sosa:Sensing and ssn:Sensing must be deleted everywhere

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                rdfs:subClassOf [ a owl:Restriction ; owl:onProperty ssn:implements ; owl:someValuesFrom ssn:Sensing ] ;
replace by sosa:Procedure

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                rdfs:subClassOf [ a owl:Restriction ; owl:onProperty sosa:observes ; owl:allValuesFrom ssn:Property ] .
replace by sosa:ObservableProperty

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                rdfs:comment "An event in the real world that 'triggers' the sensor. The properties associated to the stimulus may be different to the eventual observed property. The event, not the o
An event in the real world that 'triggers' the Sensor. The properties associated to the Stimulus may be different to the eventual observed ObservableProperty. The event, not the object, triggers the Sensor.

did we decide to keep Stimulus and SensorInput as aliases ? (they are equivalent)

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +###  http://www.w3.org/ns/ssn/ActuatorInput
What is that ?

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +###  http://www.w3.org/ns/ssn/ActuatorOutput
what is that ?

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                  rdfs:comment "The conditions a Sensor can be exposed to without damage: i.e., the Sensor continues to operate as defined using the MeasurementCapability. If, however, the SurvivalRa
The conditions a System can be exposed to without damage: i.e., the System continues to operate as defined using the MeasurementCapability. If, however, the SurvivalRange is violated, the System is 'damaged' and MeasurementCapability specifications may no longer hold.

2017-04-13 10:56 UTC, maximelefrancois86 commented on ssn/ssn_separated/ssn.ttl
> +                   rdfs:comment "Total useful life of a Sensor, Actuator or System (expressed as total life since manufacture, time in use, number of operations, etc.)." ;
Total useful life of a System (expressed as total life since manufacture, time in use, number of operations, etc.).

2017-04-14 02:11 UTC, arminhaller commented on ssn/ssn_separated/ssn.ttl
>                         rdfs:seeAlso "http://www.w3.org/2005/Incubator/ssn/wiki/SSN_Deploy#Deployment" .
Yes, I kept only the ones were I thought we haven't discussed the concepts yet. But, we can delete them all, agree.

2017-04-14 05:34 UTC, merged